# Numpy Indexing, slicing
- ndarray로부터 특정 요소를 가져오는 방법

In [1]:
import numpy as np

In [5]:
ary = [[1,2,3,4,5], [6,7,8,9,10]]
print(ary)
print(ary[0][0])

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
1


In [8]:
a = np.array(ary)
print(a)
print(a[0, 1]) #print(a[0][1])라고 해도 된다.

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


In [10]:
a[0,0] =12
print(a)

a[0, 0] = 55
print(a)

[[12  2  3  4  5]
 [ 6  7  8  9 10]]
[[55  2  3  4  5]
 [ 6  7  8  9 10]]


### Boolean Indexing
- 배열의 요소들의 값을 하나하나 조사한다.
- 특정 조건에 따라서 배열의 형태로 추출가능.
- 참, 거짓으로 결과를 구분 + 참에 해당해당하는 

In [13]:
import numpy as np

In [16]:
a = np.arange(1,25).reshape(4,6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [21]:
#짝수인지 홀수인지를 구별한다.
even_ary = a % 2 == 0
print(even_ary)

[[False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]]


In [23]:
#중요!! 간단하지만 numpy만의 독특한 연산-제2탄 같은 거랄까?
a= a[a%2 == 0] #각각의 요소들을 검사하여 짝수에 해당하는 값들만 저장한다.#이때 1차원배열로 재구성되게 된다.
print(a)

[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [24]:
a = np.arange(1,25).reshape(4,6)
a = a[even_ary] 
print(a)

[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [1]:
# Comparison을 이용한 추출

In [2]:
import numpy as np

In [14]:
a = np.array([1,4,5,2,0,3,8,9,7,6],float)
print(a)

[1. 4. 5. 2. 0. 3. 8. 9. 7. 6.]


In [15]:
print(a>4) #각 요소들의 값들이 4보다 큰지 여부를 출력.(#이것도boolean indexing인셈.) 
print(a[a>4])#이렇게 해야 각 값들이 나온다,

[False False  True False False False  True  True  True  True]
[5. 8. 9. 7. 6.]


In [16]:
b=a[a>4]
print(b)

[5. 8. 9. 7. 6.]


### Fancy indexing
- 배열에 인덱스 배열을 전달해서 요소를 추출한다.
- 인덱스 value를 이용하여 값을 출력한다.

In [18]:
import numpy as np

In [19]:
a = np.arange(1,25).reshape((4,6))
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [24]:
print(a[0,0],a[1,1],a[2,2])

1 8 15


In [27]:
b = [ a[0,0], a[1,1], a[2,2]]
print(b)

[1, 8, 15]


In [28]:
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [31]:
index1 = np.array([0,0,1,1,0])#행 역할
print(index1)#행값만 알 수 있다.
index2 = np.array([1,1,0,1,1])#열 역할
print(index2)#열값만 알 수 있다.
#(0,1)이 3개, (1,0)(#값7),(1,1)(#값8)이 1개씩 있다.
print(a[index1,index2])

[0 0 1 1 0]
[1 1 0 1 1]
[2 2 7 8 2]


In [41]:
d = np.array([[10,11], [12,13]], float)
print(d)
print()
print(d[1])#1행의 데이터들이 통째로 다 나옴
print(d[0,0])#행렬(0,0)의 값출력

[[10. 11.]
 [12. 13.]]

[12. 13.]
10.0


In [44]:
print(d)
print()
print(index1)
print()

print(d[index1]) #index1이 행을 추출하는 역할을 맡는다.
#출력결과가 아래처럼 나오는데
#[[10. 11.]
# [10. 11.]
# [12. 13.]
# [12. 13.]
# [10. 11.]]
#이는 print(d[1])(#1행의 데이터들이 통째로 다 나옴)
,print(d[2])과 같다. 
#0행의 index =[0 0 1 1 0] => 
#1행의 index =[0 0 1 1 0] =>

# index1이 열의 역할을 수행하려면?
print(d[0, index1]) #이렇게 해도 되긴 한데 조금은 아쉽다. 그래서 슬라이싱으로 확실하게 처리하게 된다.

[[10. 11.]
 [12. 13.]]

[0 0 1 1 0]

[[10. 11.]
 [10. 11.]
 [12. 13.]
 [12. 13.]
 [10. 11.]]
[10. 10. 11. 11. 10.]


## Slicing
- ndarray에서 특정 요소를 추출하는 것.
- 행과 열을 나눠서 추출가능
- 매트릭스에서 부분집합을 추출할 때 매우 유용
- 참고 : 1차원->array
-       2차원->Matrix
-       3차원이상->텐서(Tensir?)

In [45]:
import numpy as np

In [46]:
origin = np.arange(1,25).reshape(4,6)
print(origin)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [47]:
print(origin[1:3,1:5])#[1:3->7~18번이 있는 1번2번행/ 1:5->세로로2~23까지인 열]

[[ 8  9 10 11]
 [14 15 16 17]]


In [58]:
#음수 인덱스의 사용
print(origin[1:-1, 1:-1])

[[  8 999 999  11]
 [ 14 999 999  17]]


In [59]:
target = origin[1:3, 1:5]
print(target)

[[  8 999 999  11]
 [ 14 999 999  17]]


In [53]:
#target에다가 값을 넣겠다.
target[:, 1:3]
print(target)

[[ 8  9 10 11]
 [14 15 16 17]]


In [54]:
target[:, 1:3] = 999 #[:, 1:3]에 해당하는 칸들에게만 맞춰서 값을 넣는다.
print(target)

[[  8 999 999  11]
 [ 14 999 999  17]]


In [55]:
print(origin) #target은 origin데이터의 일부를 보여주는 일종의 창 역할 수행

[[  1   2   3   4   5   6]
 [  7   8 999 999  11  12]
 [ 13  14 999 999  17  18]
 [ 19  20  21  22  23  24]]


## 배열의 연산
- 기본연산자를 재정의한다.
- 이를 통해 직관적을 표현하게 된다.

In [72]:
#① +, add()
#② -, subtract()
#③ /, devide()
#④ *, multiply()
#⑤ exp()
#⑥ sqrt()
#⑦ sin()
#⑧ cos()
#⑨ tan()
#⑩ log()

In [60]:
import numpy as np

In [61]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(3,2)
print(a)
print()
print(b)

[[1 2 3]
 [4 5 6]]

[[ 7  8]
 [ 9 10]
 [11 12]]


In [62]:
print(np.dot(a,b))

[[ 58  64]
 [139 154]]


In [63]:
print(a.dot(b))

[[ 58  64]
 [139 154]]


In [65]:
c= np.random.randint(1,10,(2,3))#1이상 10미만의 정수랜덤출력한다 2행3열으로
print(c)

[[4 5 4]
 [6 9 7]]


In [66]:
print(c.T) # 대문자T는 전치행렬로 기존행렬을 뒤집는다.

[[4 6]
 [5 9]
 [4 7]]


In [67]:
#
a = np.arange(1,10).reshape(3,3)
b = np.arange(9,0,-1).reshape(3,3)
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [69]:
a > b #각각의 요소들을 일일이 낱개로 비교한다.

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [70]:
a < b #각각의 요소들을 일일이 낱개로 비교한다.

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [71]:
a == b #각각의 요소들을 일일이 낱개로 비교한다.

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [73]:
np.array_equal(a,a)

True

In [76]:
np.array_equal(a,b)

False

### aggregation

In [80]:
# sum()
# min()
# max()
# mean()
# argmax(),argmin()

In [81]:
import numpy as np

In [83]:
a = np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [85]:
np.random.shuffle(a)#원본 데이터를 마구 휘저어 랜덤화 시킨다.
print(a)

[18 14 16 13  6  5 19 15 12 17  7 10  2  1 11  8  3  4 20  9]


In [87]:
a = a.reshape(4,5)
print(a)

[[18 14 16 13  6]
 [ 5 19 15 12 17]
 [ 7 10  2  1 11]
 [ 8  3  4 20  9]]


In [88]:
np.argmax(a) #전체중에서 가장 큰 값이 배치된 위치를 표시한다. 0,1,2,3... 순으로 위치를 카운트한다

18

In [89]:
np.argmax(a, axis=0) #각 y축들에서 가장 큰 값들이 위치하는 x행의 위치값을 출력한다. #"axis=0"은 y축을 기준으로 한다는 의미. 

array([0, 1, 0, 3, 1])

In [90]:
np.argmax(a, axis=1) #각 x축들에서 가장 큰 값들이 위치하는 y열의 위치값을 출력한다. #"axis=1"은 x축을 기준으로 한다는 의미. 

array([0, 1, 4, 3])