# Numpy 배열의 변경
- append, insert, delete
    -  append, insert, delete #2개의 배열을 합쳤다. 그리고 1차원으로 차원을 축소시킨다.
- concatenate, vstack, hstack
- hsplit,vsplit

In [1]:
import numpy as np

In [2]:
a = np.arange(1,10).reshape(3,3)
b= np.arange(10,19).reshape(3,3)

In [3]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print(b)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


## 1.1. append()

In [6]:
result = np.append(a,b) #2개의 배열을 합쳤다. 그리고 1차원으로 차원을 축소시킨다.
print(result)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [7]:
print(a) #원본에는 영향을 미치지 않는다.

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# axis를 기준으로 append
# m x n^n : m=>axis 1, n=>axis 
# 주의사항 : 차원이 같아야 함.

In [10]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print(b)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [16]:
result1 = np.append(a,b,axis=0)#axis=0 : 세로를 기준으로 합쳐진다.
print(result1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [15]:
result2 = np.append(a,b,axis=1)#axis=1 : 가로를 기준으로 합쳐진다.
print(result2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


## 1.2. insert() #차원축소함

In [18]:
a = np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
np.insert(a,1,99)#a배열의 1번째 위치에 99를 넣으시오.
print("np.insert : ",np.insert(a,1,99))#이렇게 출력하려하니 안됨./출력결과 : np.insert :  <function insert at 0x10bd897a0>
#print("a : \n",a )

np.insert :  [ 1 99  2  3  4  5  6  7  8  9]


In [23]:
np.insert(a,1,555,axis=0) # 세로 한축에 모조리 555를 채운다

array([[  1,   2,   3],
       [555, 555, 555],
       [  4,   5,   6],
       [  7,   8,   9]])

In [24]:
np.insert(a,1,666,axis=1) # 세로 한축에 모조리 555를 채운다

array([[  1, 666,   2,   3],
       [  4, 666,   5,   6],
       [  7, 666,   8,   9]])

## delete()

In [26]:
a = np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
np.delete(a,1) #1번째 인덱스 삭제하면서 1차원으로 축소시킨다.
print(np.delete(a,1))

[1 3 4 5 6 7 8 9]


In [32]:
#축을 지정하면 통쨰로 날려버린다.
np.delete(a,1,axis=0) #1번째 행(axis=0)을 날려버려라. #axis라는 멘트를 안넣어도 작동한다. 사람의 가독성을 위해 굳이 axis를 명시한 것.

array([[1, 2, 3],
       [7, 8, 9]])

In [31]:
np.delete(a,1,axis=1) #1번째 열(axis=1)을 날려버려라.

array([[1, 3],
       [4, 6],
       [7, 9]])

##  2. 배열의 결합
- concatenate()
- vstack()
- hstack()

In [34]:
import numpy as np

In [36]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [37]:
np.concatenate([a, b]) # []를 통해 배열들을 묶어줘야 제대로 출력된다.

array([1, 2, 3, 4, 5, 6])

In [41]:
matrix = np.array([[1,2,3], [4,5,6]]) #[]로 감싸주는거 잊지말고!!
print(matrix)

[[1 2 3]
 [4 5 6]]


In [43]:
matrix.shape #출력결과 : (2,3) / "2행 3열의 구조이다."" 라는 의미다.

(2, 3)

In [44]:
np.concatenate([matrix,matrix])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [45]:
np.concatenate([matrix,matrix], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [46]:
np.concatenate([matrix,matrix], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [47]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
a

array([1, 2, 3])

In [49]:
a = np.array([10,11,12])

In [59]:
np.vstack([a,matrix])#행렬의 배수(MxN)가 맞으니 비로소 작동

array([[10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [60]:
np.hstack([a,matrix]) #행렬의 배수(MxN)가 맞지 않으면 에러남.

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [55]:
b = np.array([[33],[33]])

In [57]:
np.hstack([b,matrix]) 

array([[33,  1,  2,  3],
       [33,  4,  5,  6]])

In [58]:
np.vstack([b,matrix])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 1 and the array at index 1 has size 3

## 배열 분리

In [61]:
import numpy as np

In [62]:
data = np.arange(1,25).reshape(4,6)
data

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [66]:
np.hsplit(data, 2) # 한 마디로 배열이 2개로 반띵 됨.

[array([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15],
        [19, 20, 21]]),
 array([[ 4,  5,  6],
        [10, 11, 12],
        [16, 17, 18],
        [22, 23, 24]])]

In [78]:
a,b,c = np.hsplit(data, 3)
print(data)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [69]:
a

array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20]])

In [70]:
b

array([[ 3,  4],
       [ 9, 10],
       [15, 16],
       [21, 22]])

In [71]:
c

array([[ 5,  6],
       [11, 12],
       [17, 18],
       [23, 24]])

In [79]:
a,b,c,d = np.hsplit(data, [1,3,5]) # a=>[:,:1] 행은 전체, 1열만 / b=>[:,1:3] 행은전체,23열만 / c=>[:,3:5] 행은 전체 열은4,5 / d=>:,5:
#[1,3,5] : 슬라이스(컷)할 마지막 배열의 번호를 지정한 것이다.
print(data)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [80]:
a

array([[ 1],
       [ 7],
       [13],
       [19]])

In [75]:
b

array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21]])

In [76]:
c

array([[ 4,  5],
       [10, 11],
       [16, 17],
       [22, 23]])

In [77]:
d

array([[ 6],
       [12],
       [18],
       [24]])

In [81]:
r1, r2 = np.vsplit(data, 2)

In [82]:
r1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [83]:
r2

array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [85]:
r1, r2, r3 = np.vsplit(data, 3) # 정확하게 1/N이 되지 않으면 에러남.

ValueError: array split does not result in an equal division