# Numpy Indexing, slicing
- ndarray로부터 특정 요소를 가져오는 방법

In [1]:
import numpy as np

In [5]:
ary = [[1,2,3,4,5], [6,7,8,9,10]]
print(ary)
print(ary[0][0])

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
1


In [8]:
a = np.array(ary)
print(a)
print(a[0, 1]) #print(a[0][1])라고 해도 된다.

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


In [10]:
a[0,0] =12
print(a)

a[0, 0] = 55
print(a)

[[12  2  3  4  5]
 [ 6  7  8  9 10]]
[[55  2  3  4  5]
 [ 6  7  8  9 10]]


### Boolean Indexing
- 배열의 요소들의 값을 하나하나 조사한다.
- 특정 조건에 따라서 배열의 형태로 추출가능.

In [13]:
import numpy as np

In [16]:
a = np.arange(1,25).reshape(4,6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [21]:
#짝수인지 홀수인지를 구별한다.
even_ary = a % 2 == 0
print(even_ary)

[[False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]]


In [23]:
#중요!! 간단하지만 numpy만의 독특한 연산-제2탄 같은 거랄까?
a= a[a%2 == 0] #각각의 요소들을 검사하여 짝수에 해당하는 값들만 저장한다.#이때 1차원배열로 재구성되게 된다.
print(a)

[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [24]:
a = np.arange(1,25).reshape(4,6)
a = a[even_ary] 
print(a)

[ 2  4  6  8 10 12 14 16 18 20 22 24]
